# version: '3.8'

services:
  frontend:
    build:
      context: ./joblist
      dockerfile: Dockerfile
    container_name: joblist-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./joblist:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://backend:3001
    networks:
      - joblist-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  backend:
    build:
      context: ./node-testing
      dockerfile: Dockerfile
    container_name: joblist-backend
    ports:
      - "3001:3001"
    volumes:
      - ./node-testing:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://jobuser:jobpass@db:5432/joblistdb
      - JWT_SECRET=supersecret_change_me
    command: nodemon src/index.js
    networks:
      - joblist-network
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: joblistdb
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./node-testing/src/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - joblist-network

volumes:
  pgdata:

networks:
  joblist-network:
    driver: bridge