version: '3.8'
services:
  joblist:
    image: joblist:dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app  # Double-check this path matches your Dockerfile WORKDIR
      - /app/node_modules  # Isolate node_modules from host
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Required for file watching in Docker
      - WATCHPACK_POLLING=true    # Additional watch reliability
    working_dir: /app
    init: true
    stdin_open: true
    stop_signal: SIGINT
    stop_grace_period: 5s